export type CalculatorCategory = "Loans" | "Investments" | "Savings" | "Tax" | "Retirement & Planning";

type CalculatorDefinitionShape = {
  slug: string;
  name: string;
  shortName: string;
  category: CalculatorCategory;
  description: string;
  href: `/calculators/${string}`;
  metadata: { title: string; description: string };
  relatedCalculators: readonly string[];
};

export const calculators = {
  "home-loan": { slug: "home-loan", name: "Home Loan EMI Calculator", shortName: "Home Loan", category: "Loans", description: "See the monthly EMI, total interest, total repayment and month-by-month schedule for a home loan.", href: "/calculators/home-loan", metadata: { title: "Home Loan EMI Calculator | ArthaSiddhi", description: "Home loan EMI, total interest, total repayment and monthly schedule for the amount, rate and tenure entered." }, relatedCalculators: ["car-loan", "personal-loan"] },
  "car-loan": { slug: "car-loan", name: "Car Loan EMI Calculator", shortName: "Car Loan", category: "Loans", description: "Compare the EMI, total interest and total repayment for a car loan amount, rate and tenure.", href: "/calculators/car-loan", metadata: { title: "Car Loan EMI Calculator | ArthaSiddhi", description: "Car loan EMI, total interest, total repayment and monthly schedule based on the amount, rate and tenure entered." }, relatedCalculators: ["home-loan", "personal-loan"] },
  "personal-loan": { slug: "personal-loan", name: "Personal Loan EMI Calculator", shortName: "Personal Loan", category: "Loans", description: "Compare the monthly EMI, total interest and total repayment for the loan amount, rate and tenure you enter.", href: "/calculators/personal-loan", metadata: { title: "Personal Loan EMI Calculator | ArthaSiddhi", description: "Personal loan EMI, total interest and total repayment for a selected loan amount, interest rate and tenure." }, relatedCalculators: ["home-loan", "car-loan"] },
  sip: { slug: "sip", name: "SIP Calculator", shortName: "SIP", category: "Investments", description: "Enter a monthly SIP, period and assumed return to see the total invested and projected future value.", href: "/calculators/sip", metadata: { title: "SIP Calculator for Monthly Investments | ArthaSiddhi", description: "See the total invested, projected returns and future value of a monthly SIP using an assumed annual return." }, relatedCalculators: ["step-up-sip", "lumpsum"] },
  "step-up-sip": { slug: "step-up-sip", name: "Step-up SIP Calculator", shortName: "Step-up SIP", category: "Investments", description: "See how a monthly SIP that increases each year could grow at the assumed return.", href: "/calculators/step-up-sip", metadata: { title: "Step-up SIP Calculator | ArthaSiddhi", description: "Projected investment value when a monthly SIP increases once a year at the selected rate." }, relatedCalculators: ["sip", "lumpsum"] },
  lumpsum: { slug: "lumpsum", name: "Lumpsum Calculator", shortName: "Lumpsum", category: "Investments", description: "See the projected gain and future value of a one-time investment at an assumed annual return.", href: "/calculators/lumpsum", metadata: { title: "Lumpsum Investment Calculator | ArthaSiddhi", description: "Projected gain and future value of a one-time investment using an assumed annual return." }, relatedCalculators: ["sip", "cagr"] },
  cagr: { slug: "cagr", name: "CAGR Calculator", shortName: "CAGR", category: "Investments", description: "Calculate annualized growth between two values.", href: "/calculators/cagr", metadata: { title: "CAGR Calculator | Calculate Annualized Growth | ArthaSiddhi", description: "Calculate the constant annualized growth rate connecting a beginning value and ending value." }, relatedCalculators: ["lumpsum", "sip"] },
  swp: { slug: "swp", name: "SWP Calculator", shortName: "SWP", category: "Investments", description: "Check total withdrawals, the remaining balance and whether the corpus may run out during the selected period.", href: "/calculators/swp", metadata: { title: "SWP Calculator for Withdrawals and Balance | ArthaSiddhi", description: "Systematic withdrawals, remaining investment balance and possible corpus exhaustion at an assumed return." }, relatedCalculators: ["sip", "lumpsum"] },
  fd: { slug: "fd", name: "FD Calculator", shortName: "FD", category: "Savings", description: "Work out the interest and maturity amount for a fixed deposit at the chosen rate, tenure and compounding frequency.", href: "/calculators/fd", metadata: { title: "Fixed Deposit (FD) Calculator | ArthaSiddhi", description: "Fixed deposit interest and maturity amount for a selected principal, rate, tenure and compounding frequency." }, relatedCalculators: ["rd", "ppf"] },
  rd: { slug: "rd", name: "RD Calculator", shortName: "RD", category: "Savings", description: "Use a monthly deposit, rate and tenure to work out total deposits, interest and maturity amount.", href: "/calculators/rd", metadata: { title: "Recurring Deposit (RD) Calculator | ArthaSiddhi", description: "Recurring deposit interest and maturity amount based on a monthly deposit, annual rate and tenure." }, relatedCalculators: ["fd", "ppf"] },
  ppf: { slug: "ppf", name: "PPF Calculator", shortName: "PPF", category: "Savings", description: "Project total contributions, interest and maturity using an annual contribution and an editable assumed annual rate.", href: "/calculators/ppf", metadata: { title: "Public Provident Fund (PPF) Calculator | ArthaSiddhi", description: "Projected PPF contributions, interest and maturity using an annual contribution and editable assumed rate." }, relatedCalculators: ["fd", "rd", "sip"] },
  "income-tax": { slug: "income-tax", name: "Income Tax Calculator", shortName: "Income Tax", category: "Tax", description: "Estimate ordinary slab-rate tax for Tax Year 2026–27.", href: "/calculators/income-tax", metadata: { title: "Income Tax Calculator for Tax Year 2026–27 | ArthaSiddhi", description: "Estimate resident-individual income tax on ordinary slab-rate taxable income for Tax Year 2026–27." }, relatedCalculators: ["gst", "nps"] },
  gst: { slug: "gst", name: "GST Calculator", shortName: "GST", category: "Tax", description: "Add GST to or remove GST from an entered amount.", href: "/calculators/gst", metadata: { title: "GST Calculator | Add or Remove GST | ArthaSiddhi", description: "Calculate GST-exclusive or GST-inclusive amounts and split GST into CGST, SGST, or IGST." }, relatedCalculators: ["income-tax"] },
  epf: { slug: "epf", name: "EPF Contribution & Growth Calculator", shortName: "EPF", category: "Retirement & Planning", description: "See employee EPF, employer EPF/EPS allocation and a projected EPF balance using the assumptions entered.", href: "/calculators/epf", metadata: { title: "EPF Contribution and Balance Calculator | ArthaSiddhi", description: "Employee EPF, employer EPF and EPS allocation with an illustrative EPF balance projection." }, relatedCalculators: ["nps", "gratuity"] },
  nps: { slug: "nps", name: "NPS Retirement Corpus Calculator", shortName: "NPS", category: "Retirement & Planning", description: "Project an NPS corpus, lump sum, annuity allocation and illustrative monthly annuity from your contributions and assumptions.", href: "/calculators/nps", metadata: { title: "NPS Retirement Corpus Calculator | ArthaSiddhi", description: "Projected NPS corpus, lump-sum and annuity allocations, and illustrative monthly annuity based on entered assumptions." }, relatedCalculators: ["epf", "gratuity"] },
  inflation: { slug: "inflation", name: "Inflation Calculator", shortName: "Inflation", category: "Retirement & Planning", description: "See what an amount may cost later, or what its purchasing power may be after inflation.", href: "/calculators/inflation", metadata: { title: "Inflation Calculator for Future Cost and Purchasing Power | ArthaSiddhi", description: "Future cost or future purchasing power based on the current amount, period and assumed inflation rate." }, relatedCalculators: ["sip", "gratuity"] },
  gratuity: { slug: "gratuity", name: "Gratuity Calculator", shortName: "Gratuity", category: "Retirement & Planning", description: "Use eligible monthly wage and completed service to calculate a statutory-style gratuity estimate, not legal eligibility.", href: "/calculators/gratuity", metadata: { title: "Gratuity Calculator for Wage and Service | ArthaSiddhi", description: "Statutory-style gratuity estimate from eligible monthly wage and completed service, without determining legal eligibility." }, relatedCalculators: ["epf", "nps", "inflation"] },
} as const satisfies Record<string, CalculatorDefinitionShape>;

export type CalculatorSlug = keyof typeof calculators;
export type CalculatorDefinition = (typeof calculators)[CalculatorSlug];

export const calculatorCategories: CalculatorCategory[] = ["Loans", "Investments", "Savings", "Tax", "Retirement & Planning"];

export function isCalculatorSlug(slug: string): slug is CalculatorSlug { return slug in calculators; }
export function getCalculator(slug: CalculatorSlug) { return calculators[slug]; }
export function getCalculatorsByCategory(category: CalculatorCategory) { return Object.values(calculators).filter((calculator) => calculator.category === category); }
export function getRelatedCalculators(ids: readonly CalculatorSlug[]) { return ids.map((id) => calculators[id]); }
