import type { Article } from "../types";

export const loanArticles = [
  {
    title: "Home Loan Guide for Beginners",
    slug: "home-loan-guide",
    description: "What EMI, tenure, interest and lender terms mean when you compare a home loan.",
    category: "loans",
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-17",
    readingTime: "7 min read",
    maintenance: { kind: "evergreen" },
    primaryCalculator: "home-loan",
    calculatorGuideRole: "core",
    relatedCalculators: [],
    relatedArticles: ["home-loan-emi-calculation", "home-loan-tenure-comparison", "home-loan-prepayment"],
    sections: [
      {
        id: "read-cost-together",
        heading: "Read the EMI and lifetime cost together",
        paragraphs: [
          "A lower EMI can make a home loan feel easier to manage, but it does not necessarily make the loan cheaper. Before choosing a tenure or comparing offers, read the monthly payment alongside total interest and total repayment.",
          "Those figures come from the amount borrowed, interest rate and tenure. Lender charges and later changes to the loan terms can affect what you actually pay, so the EMI is a starting point rather than the whole comparison.",
        ],
      },
      {
        id: "numbers-to-read",
        heading: "The numbers to read together",
        list: [
          "Principal: the amount you borrow and need to repay.",
          "Interest rate: the rate used to calculate interest on the outstanding balance.",
          "Tenure: the period over which the scheduled repayments run.",
          "EMI: the regular monthly payment containing both principal and interest.",
          "Total interest and repayment: the interest added over the tenure and the full amount repaid through the scheduled EMIs.",
        ],
      },
      {
        id: "reducing-balance",
        heading: "How a reducing-balance EMI changes",
        paragraphs: [
          "In a monthly reducing-balance loan, interest is calculated on the principal still outstanding. Part of each EMI pays that interest and the rest reduces principal, leaving a lower balance for the next month.",
          [
            { text: "Early EMIs therefore contain more interest, while later EMIs usually direct more money to principal when the rate and payment stay unchanged. See " },
            { text: "how a home-loan EMI is calculated", link: { kind: "article", slug: "home-loan-emi-calculation" } },
            { text: " for the formula and an amortization example." },
          ],
        ],
      },
      {
        id: "worked-example",
        heading: "Worked example: ₹40 lakh for 20 years",
        paragraphs: [
          "Consider a ₹40,00,000 loan at 8.5% a year for 20 years, calculated on a monthly reducing balance. With a constant rate, regular monthly payments and no fees or prepayments, the rounded figures are:",
        ],
        table: {
          caption: "Illustrative ₹40 lakh home loan at 8.5% for 20 years",
          headers: ["Monthly EMI", "Total interest", "Total repayment"],
          rows: [["₹34,713", "₹43,31,103", "₹83,31,103"]],
        },
      },
      {
        id: "tenure-and-terms",
        heading: "A longer tenure changes more than the EMI",
        paragraphs: [
          "Spreading the same loan over more months usually lowers the EMI. But the balance remains outstanding for longer, so total interest can rise. The lower monthly payment and the higher lifetime cost need to be considered together.",
          [
            { text: "The worked example above shows why affordability cannot be judged from ₹34,713 alone: interest adds ₹43,31,103 over the full tenure under these assumptions. The " },
            { text: "home-loan tenure comparison", link: { kind: "article", slug: "home-loan-tenure-comparison" } },
            { text: " shows this trade-off across several tenures without changing the loan amount or rate." },
          ],
          "A floating rate can also change the EMI, tenure or both after the loan starts. Check how the lender handles rate changes instead of assuming the opening schedule will remain fixed.",
        ],
      },
      {
        id: "offer-checklist",
        heading: "What to check before accepting an offer",
        paragraphs: [
          [
            { text: "If you may repay extra later, read the lender’s prepayment terms and how a part-payment would change the schedule. The " },
            { text: "home-loan prepayment guide", link: { kind: "article", slug: "home-loan-prepayment" } },
            { text: " explains the questions to ask without assuming every lender treats prepayment the same way." },
          ],
        ],
        list: [
          "Rate type and how a rate reset may affect the EMI or tenure.",
          "EMI, tenure, total interest and total repayment for the same loan amount.",
          "Processing, legal, valuation, insurance and other applicable charges.",
          "Prepayment and foreclosure terms, including any conditions or charges.",
          "Figures and conditions in the sanction letter, loan agreement and repayment schedule.",
        ],
      },
      {
        id: "compare-your-scenario",
        heading: "Compare one actual loan scenario",
        paragraphs: [
          "Use the amount, rate and tenure from an offer you are considering. Start with the EMI, then read the total interest and total repayment. Change the rate or tenure one at a time to see what moves.",
        ],
        callout: {
          title: "Check the EMI and full-tenure cost",
          text: [
            { text: "Enter the offer’s figures in the " },
            { text: "Home Loan EMI Calculator", link: { kind: "calculator", slug: "home-loan" } },
            { text: "." },
          ],
        },
      },
    ],
    faq: [
      { question: "What should I check before planning a home-loan prepayment?", answer: "Check how the lender will apply the amount, whether the EMI or tenure will change, when the revised schedule starts and whether any conditions or charges apply. Ask for the updated repayment schedule after the payment is posted." },
    ],
  },
  {
    title: "How Home Loan EMI Is Calculated: Principal, Interest and Reducing Balance",
    slug: "home-loan-emi-calculation",
    description: "How the home-loan EMI formula works, why the principal and interest split changes each month, and what an amortization schedule shows.",
    category: "loans",
    publishedAt: "2026-08-16",
    updatedAt: "2026-08-16",
    readingTime: "8 min read",
    maintenance: { kind: "evergreen" },
    primaryCalculator: "home-loan",
    calculatorGuideRole: "supporting",
    relatedCalculators: [],
    relatedArticles: ["home-loan-guide", "home-loan-tenure-comparison"],
    sections: [
      { id: "what-an-emi-contains", heading: "What a home-loan EMI contains", paragraphs: ["A home-loan EMI has two parts: interest for the period and repayment of principal. The EMI may stay constant when the rate and tenure stay constant, but the split between those two parts changes each month.", "Under a monthly reducing-balance loan, the month’s interest is calculated on the outstanding principal. The rest of the EMI reduces that principal, so the next month starts with a slightly lower balance."] },
      { id: "emi-formula", heading: "The EMI formula", paragraphs: ["For a standard monthly amortizing loan, EMI = [P × r × (1 + r)^n] ÷ [(1 + r)^n − 1].", "Here, P is the loan principal, r is the monthly interest rate, and n is the total number of monthly instalments. The formula sets one regular payment that repays the principal and calculated interest over the selected tenure, subject to the stated assumptions."] },
      { id: "monthly-rate-and-instalments", heading: "Monthly rate and number of instalments", paragraphs: ["If the annual interest rate is R per cent, the monthly rate used by this model is r = R ÷ 12 ÷ 100. A 20-year tenure has 240 monthly instalments, so n is 240.", "The monthly rate is a decimal in the formula. For example, 8.5% a year becomes 0.085 ÷ 12, or about 0.0070833 per month."] },
      { id: "reducing-balance", heading: "What monthly reducing balance means", paragraphs: ["Interest is not repeatedly calculated on the original loan amount. It is calculated on the principal still outstanding for that month. After the principal component of an EMI is deducted, the lower balance is used for the next month’s interest.", "This is why the interest component normally falls and the principal component normally rises over the schedule when the EMI and rate do not change."] },
      { id: "worked-example", heading: "Worked example: the first three EMIs", paragraphs: ["Consider a ₹10,00,000 loan at 8.5% a year for 20 years. Using the same monthly reducing-balance convention as the ArthaSiddhi Home Loan EMI Calculator, the EMI is ₹8,678 when rounded to the nearest rupee. Each value in the table is rounded separately, so the displayed principal and interest may differ from the displayed EMI by ₹1."], table: { caption: "First three months of the illustrative ₹10 lakh loan", headers: ["Month", "EMI", "Interest", "Principal", "Balance after EMI"], rows: [["1", "₹8,678", "₹7,083", "₹1,595", "₹9,98,405"], ["2", "₹8,678", "₹7,072", "₹1,606", "₹9,96,799"], ["3", "₹8,678", "₹7,061", "₹1,618", "₹9,95,181"]] } },
      { id: "early-emis", heading: "Why early EMIs contain more interest", paragraphs: ["At the start, almost the full principal is outstanding. Applying the monthly rate to that larger balance produces a larger interest amount, leaving less of the EMI for principal.", "Later in the loan, the outstanding principal is lower. Monthly interest is then lower too, so more of the same EMI can reduce principal."] },
      { id: "amortization-schedule", heading: "What the amortization schedule shows", paragraphs: ["An amortization schedule lists each EMI, its principal and interest components, and the outstanding balance after payment. It lets you see the shift in the EMI split rather than treating the EMI as one unexplained number.", "A floating-rate reset, a missed payment, a prepayment, lender rounding or a different interest-accrual convention can change the actual schedule."] },
      { id: "costs-outside-emi", heading: "What the EMI formula does not include", paragraphs: ["The formula above covers principal and interest under its assumptions. It does not automatically include processing fees, legal or valuation charges, insurance, switching charges, penalties or every other borrowing cost.", "For applicable retail term loans, the lender’s Key Facts Statement should show key terms and the annual percentage rate, which reflects the all-in cost covered by the KFS rules. Check the KFS, sanction letter and loan agreement for the actual costs attached to an offer."], callout: { title: "Calculate the full schedule", text: [{ text: "Enter your loan amount, rate and tenure in the " }, { text: "Home Loan EMI Calculator", link: { kind: "calculator", slug: "home-loan" } }, { text: " to see the EMI, total interest and month-by-month schedule." }] } },
    ],
    faq: [
      { question: "Why does the interest part fall even when the EMI stays the same?", answer: "Each principal payment reduces the outstanding balance. Under a monthly reducing-balance model, the next month’s interest is calculated on that lower balance." },
      { question: "Will a lender’s schedule always match a calculator exactly?", answer: "Not always. Payment dates, rate resets, daily or monthly accrual, rounding and lender-specific terms can create differences. Use the lender’s repayment schedule for the contractual figures." },
    ],
    references: [
      { title: "Housing Loans — FAQs", publisher: "Reserve Bank of India", url: "https://rbi.org.in/CommonPerson/english/scripts/FAQs.aspx?Id=701", sourceType: "official", accessedAt: "2026-08-16" },
      { title: "Key Facts Statement (KFS) for Loans & Advances", publisher: "Reserve Bank of India", url: "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12663&Mode=0", sourceType: "official", accessedAt: "2026-08-16" },
    ],
  },
  {
    title: "Home Loan Tenure: 15 vs 20 vs 25 vs 30 Years",
    slug: "home-loan-tenure-comparison",
    description: "A ₹50 lakh home-loan comparison showing how 15, 20, 25 and 30-year tenures change the EMI and total interest at the same rate.",
    category: "loans",
    publishedAt: "2026-08-16",
    updatedAt: "2026-08-16",
    readingTime: "7 min read",
    maintenance: { kind: "evergreen" },
    primaryCalculator: "home-loan",
    calculatorGuideRole: "supporting",
    relatedCalculators: [],
    relatedArticles: ["home-loan-guide", "home-loan-emi-calculation", "home-loan-prepayment"],
    sections: [
      { id: "comparison", heading: "The 15, 20, 25 and 30-year comparison", paragraphs: ["This example keeps the loan amount and rate unchanged: ₹50,00,000 at 8.5% a year on a monthly reducing balance. It assumes a constant rate, regular monthly EMIs, no prepayment, no missed payments and no fees or charges."], table: { caption: "₹50 lakh home loan at 8.5% a year", headers: ["Tenure", "Monthly EMI", "Total interest"], rows: [["15 years", "₹49,237", "₹38,62,656 (₹38.63 lakh)"], ["20 years", "₹43,391", "₹54,13,879 (₹54.14 lakh)"], ["25 years", "₹40,261", "₹70,78,406 (₹70.78 lakh)"], ["30 years", "₹38,446", "₹88,40,443 (₹88.40 lakh)"]] } },
      { id: "why-emi-falls", heading: "Why a longer tenure lowers the EMI", paragraphs: ["The same principal is spread over more monthly instalments. That reduces the amount due each month, although interest continues to be charged while the balance remains outstanding.", "The EMI reduction becomes progressively smaller in this example. Moving from 15 to 20 years lowers the displayed EMI by ₹5,846, while moving from 25 to 30 years lowers it by ₹1,815."] },
      { id: "why-interest-rises", heading: "Why total interest rises", paragraphs: ["A longer tenure keeps principal outstanding for more months. Even though each EMI is lower, interest is calculated over a longer period, so the total can rise substantially.", "The 30-year option in this example has a displayed EMI ₹4,945 lower than the 20-year option. Its total interest is ₹34,26,564 higher, or about ₹34.27 lakh. The monthly reduction and the lifetime increase need to be read together."] },
      { id: "rate-reset", heading: "A floating rate can change the comparison", paragraphs: ["The table assumes 8.5% throughout. A floating-rate home loan may reset during its tenure, changing the EMI, the number of instalments, or both.", "For applicable EMI-based floating-rate loans, RBI instructions require the regulated entity to communicate the impact of a reset and provide the applicable options. These can include a higher EMI, longer tenure, a combination, switching to a fixed rate under the lender’s policy, and part or full prepayment. The lender should not be assumed to apply one outcome in every case."] },
      { id: "choosing-tenure", heading: "There is no single correct tenure", paragraphs: ["A shorter tenure needs a higher monthly payment but reduces the time over which interest accrues. A longer tenure lowers the required EMI but can leave less room for future rate increases and can materially raise total interest.", "The suitable tenure depends on cash flow, other essential commitments and the loan terms. This comparison does not recommend one tenure for every borrower."] },
      { id: "compare-own-numbers", heading: "Compare your own amount and rate", paragraphs: ["A ₹50 lakh example cannot represent every loan. Changing the amount or rate can materially change both the EMI and the gap between tenures."], callout: { title: "Test another tenure", text: [{ text: "Use the " }, { text: "Home Loan EMI Calculator", link: { kind: "calculator", slug: "home-loan" } }, { text: " to compare the EMI, total interest and repayment schedule for your own inputs." }] } },
    ],
    faq: [
      { question: "Does the lowest EMI mean the lowest-cost tenure?", answer: "No. A lower EMI commonly comes from spreading repayment over more months, which can increase total interest. Compare both figures." },
      { question: "Does the table predict what a floating-rate loan will cost?", answer: "No. It holds the rate at 8.5% for the full tenure. Actual floating rates and the resulting repayment schedule can change." },
    ],
    references: [
      { title: "Housing Loans — FAQs", publisher: "Reserve Bank of India", url: "https://rbi.org.in/CommonPerson/english/scripts/FAQs.aspx?Id=701", sourceType: "official", accessedAt: "2026-08-16" },
      { title: "FAQs on Reset of Floating Interest Rate on EMI-based Personal Loans", publisher: "Reserve Bank of India", url: "https://www.rbi.org.in/commonman/Upload/English/FAQs/PDFs/FAQRFIR10012025.pdf", sourceType: "official", accessedAt: "2026-08-16" },
    ],
  },
  {
    title: "How Home Loan Prepayment Changes Principal, Tenure and Interest",
    slug: "home-loan-prepayment",
    description: "What a home-loan part-prepayment does to outstanding principal, future interest, EMI and tenure, subject to the lender’s terms.",
    category: "loans",
    publishedAt: "2026-08-16",
    updatedAt: "2026-08-16",
    readingTime: "7 min read",
    maintenance: { kind: "evergreen" },
    primaryCalculator: "home-loan",
    calculatorGuideRole: "supporting",
    relatedCalculators: [],
    relatedArticles: ["home-loan-guide", "home-loan-tenure-comparison"],
    sections: [
      { id: "what-prepayment-does", heading: "What a part-prepayment does", paragraphs: ["A part-prepayment is an amount paid in addition to the scheduled EMI and applied to outstanding principal. Once the lender applies it, the principal used for later interest calculations is lower.", "This is different from paying an EMI early. Confirm how the lender will identify and apply the additional amount before transferring it."] },
      { id: "why-interest-can-fall", heading: "Why future interest can fall", paragraphs: ["Under a monthly reducing-balance convention, interest for a month is calculated on the outstanding principal. Reducing that principal earlier means later interest starts from a lower base.", "The actual saving depends on when the prepayment is credited, the amount, future rates, the remaining tenure, the lender’s recalculation method and whether the EMI or tenure changes. This article does not calculate an individual saving."] },
      { id: "what-can-change", heading: "What may happen after prepayment", paragraphs: ["The lender’s terms and the borrower’s permitted instruction determine the revised schedule. Do not assume that every lender automatically reduces tenure or automatically reduces EMI."], table: { caption: "Common ways a revised schedule may be handled", headers: ["Possible treatment", "What it generally means", "What to confirm"], rows: [["Tenure reduces", "EMI stays similar and fewer instalments remain", "Revised final payment date"], ["EMI reduces", "Tenure stays similar and the required monthly payment falls", "Revised EMI and effective date"], ["Another permitted treatment", "The lender applies its documented process or an available borrower instruction", "How the amount is allocated and when the revised schedule starts"]] } },
      { id: "floating-rate-reset", heading: "Floating-rate resets and borrower options", paragraphs: ["For applicable EMI-based floating-rate loans, RBI instructions require regulated entities to communicate the effect of benchmark-rate resets. The available options can include increasing EMI, extending tenure, using a combination, switching to fixed rate under the lender’s policy, and part or full prepayment.", "Those reset options do not mean every lender handles an ordinary voluntary prepayment in exactly the same way. Ask for the revised amortization schedule after the amount is applied."] },
      { id: "charges", heading: "Check whether a charge can apply", paragraphs: ["Do not assume that every loan can be prepaid without a charge. RBI protections restrict prepayment charges for applicable floating-rate loans, including specified protections for individuals borrowing for non-business purposes. Treatment outside the protected cases can depend on the lender category, whether the loan is fixed, floating or dual-rate, when it was sanctioned or renewed, and the applicable rules and loan terms.", "For loans sanctioned or renewed on or after 1 January 2026, the RBI’s 2025 Directions set the current framework across covered regulated entities. For a dual or special-rate loan, the rate structure at the time of prepayment matters. Check the lender’s current terms rather than relying on a general statement."] },
      { id: "documents-to-check", heading: "Documents and instructions to check", list: ["Sanction letter: the approved rate structure, tenure and conditions.", "Key Facts Statement: applicable key terms, APR and disclosed charges.", "Loan agreement: the prepayment or foreclosure clause and reset terms.", "Current lender instructions: minimum amount, notice, payment route and schedule-revision process.", "Revised amortization schedule: how principal, EMI and remaining tenure changed after posting."] },
      { id: "calculator-scope", heading: "What the current calculator can show", paragraphs: ["ArthaSiddhi does not currently have a dedicated prepayment calculator. The existing calculator can show the original EMI, total interest and schedule for an amount, rate and tenure, but it does not estimate savings from a later part-prepayment."], callout: { title: "Review the original loan schedule", text: [{ text: "Open the " }, { text: "Home Loan EMI Calculator", link: { kind: "calculator", slug: "home-loan" } }, { text: " to view the monthly reducing-balance schedule before considering any lender-specific prepayment treatment." }] } },
    ],
    faq: [
      { question: "Does a part-prepayment always reduce the tenure?", answer: "No. The lender may reduce tenure, reduce EMI, or apply another permitted treatment according to its terms and the available borrower instruction. Ask for the revised schedule." },
      { question: "Is home-loan prepayment always free?", answer: "No blanket statement covers every loan. Current RBI protections apply to specified cases, while fixed, dual-rate or otherwise excluded loans can follow different terms. Check the sanction letter, KFS, agreement and current lender instructions." },
    ],
    references: [
      { title: "Housing Loans — FAQs", publisher: "Reserve Bank of India", url: "https://rbi.org.in/CommonPerson/english/scripts/FAQs.aspx?Id=701", sourceType: "official", accessedAt: "2026-08-16" },
      { title: "FAQs on Reset of Floating Interest Rate on EMI-based Personal Loans", publisher: "Reserve Bank of India", url: "https://www.rbi.org.in/commonman/Upload/English/FAQs/PDFs/FAQRFIR10012025.pdf", sourceType: "official", accessedAt: "2026-08-16" },
      { title: "Reserve Bank of India (Pre-payment Charges on Loans) Directions, 2025", publisher: "Reserve Bank of India", url: "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12878&Mode=0", sourceType: "official", accessedAt: "2026-08-16" },
      { title: "Key Facts Statement (KFS) for Loans & Advances", publisher: "Reserve Bank of India", url: "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12663&Mode=0", sourceType: "official", accessedAt: "2026-08-16" },
    ],
  },
] satisfies readonly Article[];
