import { calculateIncomeTax } from "../../calculator/rule-driven-calculators";
import { incomeTaxRuleSet } from "../../financial-rules/rule-sets";
import type { Article } from "../types";

const ruleSetId = incomeTaxRuleSet.id;
const calculateNewRegime = (taxableOrdinaryIncome: number) => calculateIncomeTax({ regime: "new", ageCategory: "below-60", taxableOrdinaryIncome }, incomeTaxRuleSet);
const coreExample = calculateNewRegime(1_500_000);
const rebateExamples = [1_200_000, 1_200_001, 1_250_000, 1_270_588].map(calculateNewRegime);
const cessExample = calculateNewRegime(1_300_000);
const money = (value: number) => `₹${new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(value)}`;
const taxRows = (results: readonly ReturnType<typeof calculateNewRegime>[]) => results.map((result) => [money(result.taxableIncome), money(result.taxBeforeRebate), money(result.rebate), money(result.marginalRelief), money(result.taxAfterRelief), money(result.cess), money(result.totalTax)]);

export const taxArticles = [
  {
    title: "New Tax Regime Slabs: How Income Tax Is Calculated",
    slug: "new-tax-regime-slab-calculation",
    description: "New Tax Regime slab calculation for Tax Year 2026–27, including progressive rates, resident-individual relief, cess and calculator limits.",
    category: "tax",
    publishedAt: "2026-08-18",
    updatedAt: "2026-08-23",
    readingTime: "9 min read",
    maintenance: { kind: "rule-sensitive", ruleSetId },
    primaryCalculator: "income-tax",
    calculatorGuideRole: "core",
    relatedCalculators: [],
    relatedArticles: ["section-87a-rebate", "health-education-cess-calculation", "gross-income-vs-taxable-income", "income-tax-calculator-vs-payroll-tds"],
    sections: [
      { id: "answer", heading: "Tax is charged progressively, not at one rate on all income", paragraphs: ["For Tax Year 2026–27 (the financial year from 1 April 2026 to 31 March 2027), taxable ordinary income is divided across the new-regime slabs in section 202 of the Income-tax Act, 2025. Each slice is taxed at its own rate. The highest rate reached is not applied to the entire amount.", [{ text: "Enter an already-determined taxable ordinary income amount in the " }, { text: "Income Tax Calculator", link: { kind: "calculator", slug: "income-tax" } }, { text: ". The tool calculates slab tax, the applicable resident-individual rebate or marginal relief under section 156, then 4% Health & Education Cess." }]] },
      { id: "slabs", heading: "New-regime slabs for the supported period", table: { caption: "Tax Year 2026–27 new-regime ordinary-income slabs", headers: ["Taxable income slice", "Rate"], rows: [["Up to ₹4,00,000", "Nil"], ["₹4,00,001–₹8,00,000", "5%"], ["₹8,00,001–₹12,00,000", "10%"], ["₹12,00,001–₹16,00,000", "15%"], ["₹16,00,001–₹20,00,000", "20%"], ["₹20,00,001–₹24,00,000", "25%"], ["Above ₹24,00,000", "30%"]] }, paragraphs: ["A rate applies only to the part of income inside its band. The amounts from all occupied bands are added to produce slab tax."] },
      { id: "worked-example", heading: "Worked example: ₹15 lakh of taxable ordinary income", paragraphs: ["Assume ₹15,00,000 of taxable ordinary income under the new regime. This is an engine-generated illustration for the supported period; it does not derive taxable income from salary or other receipts."], table: { caption: "Engine result for ₹15,00,000", headers: ["Slab tax", "Resident-individual rebate", "Marginal relief", "Tax after relief", "4% cess", "Estimated total tax"], rows: [[money(coreExample.taxBeforeRebate), money(coreExample.rebate), money(coreExample.marginalRelief), money(coreExample.taxAfterRelief), money(coreExample.cess), money(coreExample.totalTax)]] } },
      { id: "read-sequence", heading: "Read the result in statutory sequence", paragraphs: ["The ₹1,05,000 slab tax comes from adding tax across the occupied bands. At this income there is no ordinary rebate or marginal relief, so tax after relief remains ₹1,05,000. Cess is ₹4,200, producing an estimated total of ₹1,09,200.", [{ text: "The threshold rules are explained in the " }, { text: "resident-individual rebate guide", link: { kind: "article", slug: "section-87a-rebate" } }, { text: ", while the " }, { text: "cess guide", link: { kind: "article", slug: "health-education-cess-calculation" } }, { text: " explains why cess is applied after relief rather than to taxable income." }]] },
      { id: "scope", heading: "What this calculation includes—and leaves out", paragraphs: ["Within its ₹50 lakh ceiling, the calculator supports a selected old or new regime, age-sensitive old-regime slabs, ordinary slab-rate taxable income, the configured resident-individual rebate and new-regime marginal relief, and Health & Education Cess.", "It expects taxable ordinary income as an input. It does not derive gross salary, standard deduction, other deductions or exemptions; compute house-property or business income; classify capital gains, crypto/VDA, lottery or other special-rate income; or aggregate agricultural income.", "It also does not model surcharge or surcharge marginal relief, determine residential or NRI status, simulate TDS/TCS or payroll withholding, calculate advance tax, tax paid, refund, salary-arrears relief, foreign-tax or treaty relief, return-filing liability, or every statutory filing and payment rounding convention."], callout: { title: "Start with the right input", text: [{ text: "Read " }, { text: "gross income versus taxable income", link: { kind: "article", slug: "gross-income-vs-taxable-income" } }, { text: " before entering a salary figure. For withholding differences, see " }, { text: "calculator estimate versus payroll TDS", link: { kind: "article", slug: "income-tax-calculator-vs-payroll-tds" } }, { text: "." }] } },
    ],
    faq: [{ question: "Is the highest slab rate charged on the whole income?", answer: "No. Each rate applies only to the taxable-income slice within that slab." }, { question: "Does this calculator prepare an income-tax return?", answer: "No. It estimates tax for a supported ordinary-income input and does not perform a complete filing computation." }],
  },
  {
    title: "Resident-Individual Tax Rebate Explained for Tax Year 2026–27",
    slug: "section-87a-rebate",
    description: "How the Tax Year 2026–27 resident-individual rebate, ₹60,000 cap and marginal relief work for supported new-regime ordinary income.",
    category: "tax", publishedAt: "2026-08-18", updatedAt: "2026-08-23", readingTime: "8 min read",
    maintenance: { kind: "rule-sensitive", ruleSetId }, primaryCalculator: "income-tax", calculatorGuideRole: "supporting", calculatorDiscoveryPriority: 100, relatedCalculators: [], relatedArticles: ["new-tax-regime-slab-calculation", "health-education-cess-calculation"],
    sections: [
      { id: "eligibility", heading: "The ₹12 lakh rule is conditional", paragraphs: ["For Tax Year 2026–27, section 156 of the Income-tax Act, 2025 allows a resident individual whose total income is chargeable under the section 202 new regime a rebate equal to the eligible calculated tax, capped at ₹60,000, when total income does not exceed ₹12,00,000. This is the current counterpart of the rebate previously associated with section 87A of the Income-tax Act, 1961.", "Within this calculator's supported ordinary slab-income scenario, slab tax at ₹12,00,000 is ₹60,000 and the ordinary rebate reduces it to zero before cess. This should not be restated as everyone earning ₹12 lakh always pays zero tax: the official provision limits the rebate to tax payable at ordinary new-regime slab rates, while this calculator does not classify or calculate special-rate income."] },
      { id: "examples", heading: "What happens at and above ₹12 lakh", paragraphs: ["The examples below come directly from the current Income Tax engine. Marginal relief limits tax after relief to the amount by which income exceeds ₹12 lakh while the ordinary slab tax is higher than that excess."], table: { caption: "Section 156 engine examples for ordinary new-regime income", headers: ["Income", "Slab tax", "Ordinary rebate", "Marginal relief", "Tax after relief", "Cess", "Final estimate"], rows: taxRows(rebateExamples) } },
      { id: "cliff", heading: "₹12,00,001 does not create a ₹60,000 tax cliff", paragraphs: ["At ₹12,00,001, ordinary rebate is zero, but marginal relief reduces ₹60,000.15 of slab tax by ₹59,999.15. Tax after relief is ₹1; 4% cess is ₹0.04; the final estimate is ₹1.04.", "At ₹12,50,000, marginal relief is ₹17,500 and tax after relief is ₹50,000. Near the crossover, ₹12,70,588 still receives ₹0.20 of marginal relief. From the point where ordinary slab tax is no higher than income above ₹12 lakh, marginal relief no longer changes the result."], callout: { title: "Check the full slab sequence", text: [{ text: "Use the " }, { text: "Income Tax Calculator", link: { kind: "calculator", slug: "income-tax" } }, { text: " for an entered scenario, or review " }, { text: "how the new-regime slabs are calculated", link: { kind: "article", slug: "new-tax-regime-slab-calculation" } }, { text: "." }] } },
      { id: "cess", heading: "Relief comes before cess", paragraphs: [[{ text: "Cess is calculated on tax after the applicable rebate or marginal relief. The " }, { text: "4% cess explanation", link: { kind: "article", slug: "health-education-cess-calculation" } }, { text: " shows this order separately." }]] },
    ],
    faq: [{ question: "Is marginal relief the same as the ordinary ₹60,000 rebate?", answer: "No. The ordinary rebate applies at or below the threshold subject to its cap. Marginal relief applies just above the threshold when calculated slab tax exceeds the income above ₹12 lakh." }, { question: "Does the example cover capital gains or other special-rate income?", answer: "No. It covers ordinary slab-rate taxable income only; the calculator does not classify or compute special-rate income." }],
  },
  {
    title: "Health & Education Cess: How the 4% Cess Is Calculated",
    slug: "health-education-cess-calculation",
    description: "Why Health & Education Cess is 4% of tax after applicable relief, rather than 4% of taxable income.",
    category: "tax", publishedAt: "2026-08-18", updatedAt: "2026-08-23", readingTime: "6 min read",
    maintenance: { kind: "rule-sensitive", ruleSetId }, primaryCalculator: "income-tax", calculatorGuideRole: "supporting", relatedCalculators: [], relatedArticles: ["new-tax-regime-slab-calculation", "section-87a-rebate"],
    sections: [
      { id: "base", heading: "The 4% rate applies to tax, not taxable income", paragraphs: ["For Tax Year 2026–27, Health & Education Cess is calculated at 4% on income tax plus surcharge where surcharge applies. It is not 4% of taxable income.", "The ArthaSiddhi calculator stops at ₹50 lakh and does not model surcharge. In its supported examples, the cess base is therefore income tax after the applicable section 156 rebate or marginal relief."] },
      { id: "example", heading: "Example: ₹13 lakh under the new regime", paragraphs: ["For ₹13,00,000 of taxable ordinary income, the engine calculates slab tax of ₹75,000. Marginal relief has ceased at this point, so tax after relief remains ₹75,000. Cess is 4% of ₹75,000, or ₹3,000—not 4% of ₹13,00,000."], table: { caption: "Engine result for ₹13,00,000", headers: ["Slab tax", "Rebate", "Marginal relief", "Tax after relief", "4% cess", "Final estimate"], rows: [[money(cessExample.taxBeforeRebate), money(cessExample.rebate), money(cessExample.marginalRelief), money(cessExample.taxAfterRelief), money(cessExample.cess), money(cessExample.totalTax)]] } },
      { id: "order", heading: "Why calculation order matters", paragraphs: ["Applying cess before rebate or marginal relief would overstate the supported result. The engine first calculates slabs, then relief, and only then cess."], callout: { title: "See the connected calculations", text: [{ text: "Read the " }, { text: "new-regime slab guide", link: { kind: "article", slug: "new-tax-regime-slab-calculation" } }, { text: " and the " }, { text: "resident-individual rebate explanation", link: { kind: "article", slug: "section-87a-rebate" } }, { text: ", or test an ordinary-income scenario in the " }, { text: "Income Tax Calculator", link: { kind: "calculator", slug: "income-tax" } }, { text: "." }] } },
    ],
    faq: [{ question: "Is cess 4% of taxable income?", answer: "No. It is 4% of income tax plus surcharge where applicable, after applicable relief in the supported calculation sequence." }, { question: "Does the calculator include surcharge in the cess base?", answer: "No. Surcharge is outside scope and income input is capped at ₹50 lakh." }],
  },
  {
    title: "Gross Income vs Taxable Income: What Goes Into a Tax Calculator",
    slug: "gross-income-vs-taxable-income",
    description: "Why gross salary, gross income and the taxable ordinary income expected by a tax calculator are not interchangeable figures.",
    category: "tax", publishedAt: "2026-08-18", updatedAt: "2026-08-23", readingTime: "6 min read",
    maintenance: { kind: "rule-sensitive", ruleSetId }, primaryCalculator: "income-tax", calculatorGuideRole: "supporting", calculatorDiscoveryPriority: 50, relatedCalculators: [], relatedArticles: ["new-tax-regime-slab-calculation", "income-tax-calculator-vs-payroll-tds"],
    sections: [
      { id: "input", heading: "The calculator expects taxable ordinary income", paragraphs: ["Gross salary is not automatically the number to enter. Salary components, other income, permitted exclusions, deductions and the applicable tax treatment can affect the amount eventually chargeable to ordinary slab rates.", "The ArthaSiddhi calculator expects an already-determined taxable ordinary income amount. It applies the selected regime's supported slabs and relief to that input; it does not turn payslip components or gross receipts into taxable income."] },
      { id: "distinctions", heading: "Keep the income labels separate", table: { caption: "Conceptual distinctions, not a personal computation", headers: ["Term", "What it describes here"], rows: [["Gross salary", "Salary components before completing the relevant tax computation"], ["Gross or total income", "Broader statutory concepts whose treatment depends on income composition and applicable provisions"], ["Taxable ordinary income input", "The already-determined amount within this calculator's ordinary slab-rate scope"]] } },
      { id: "not-derived", heading: "What the calculator does not derive", paragraphs: ["It does not calculate the standard deduction, HRA or other exemptions, other statutory deductions, house-property results, business or professional income, or residential status. It also does not identify capital gains, crypto/VDA, lottery or other special-rate income.", [{ text: "Once the supported input is known, the " }, { text: "new-regime slab guide", link: { kind: "article", slug: "new-tax-regime-slab-calculation" } }, { text: " explains what happens next. The " }, { text: "Income Tax Calculator", link: { kind: "calculator", slug: "income-tax" } }, { text: " should not be used to invent the input." }]] },
      { id: "payroll", heading: "A payroll figure may serve a different purpose", paragraphs: [[{ text: "An employer's estimated salary and withholding process can use declarations and information available during the year. Read why that process can differ from an " }, { text: "annual calculator estimate", link: { kind: "article", slug: "income-tax-calculator-vs-payroll-tds" } }, { text: "." }]] },
    ],
    faq: [{ question: "Can I enter annual CTC as taxable income?", answer: "Not automatically. CTC and taxable ordinary income are different concepts; determine the supported taxable amount before using the calculator." }, { question: "Will the calculator apply my deductions and exemptions?", answer: "No. Any applicable deductions and exemptions must already be reflected in the entered amount." }],
  },
  {
    title: "Why an Income Tax Calculator May Differ From Payroll TDS",
    slug: "income-tax-calculator-vs-payroll-tds",
    description: "Why an annual income-tax estimate may differ from employer TDS shown on a payslip during the financial year.",
    category: "tax", publishedAt: "2026-08-18", updatedAt: "2026-08-23", readingTime: "7 min read",
    maintenance: { kind: "rule-sensitive", ruleSetId }, primaryCalculator: "income-tax", calculatorGuideRole: "supporting", relatedCalculators: [], relatedArticles: ["new-tax-regime-slab-calculation", "gross-income-vs-taxable-income"],
    references: [{ title: "Income-tax Act, 2025 — section 392: salary withholding", publisher: "Income Tax Department", url: "https://www.incometaxindia.gov.in/w/section-392-5", sourceType: "official", accessedAt: "2026-08-23" }],
    sections: [
      { id: "difference", heading: "Annual tax estimate and payroll withholding are different processes", paragraphs: ["The calculator estimates annual tax from the taxable ordinary income and regime entered. Payroll TDS is tax deducted by an employer at payment based on estimated salary income for the financial year and information available to payroll. One payslip's deduction therefore need not equal one-twelfth of this calculator's annual result.", "A difference by itself does not prove that either figure is wrong. Compare the assumptions, period, regime, income included and tax already deducted."] },
      { id: "why", heading: "Why payroll estimates can change during the year", list: ["Salary changes, bonus timing, arrears and taxable perquisites can change the employer's projection.", "Declarations and later proof submission can change claims reflected in payroll.", "Previous-employer salary and TDS affect the estimate when the employee supplies those details.", "Other income reported to the employer and the regime applied can change the calculation.", "Section 392 permits adjustment of an earlier excess or deficiency during the tax year." ] },
      { id: "compare", heading: "What to compare before treating a difference as an error", paragraphs: ["Check whether both figures use Tax Year 2026–27, the same regime and the same annual income assumptions. Review salary changes, bonus, arrears, perquisites, declarations, proof status, previous-employer details, other income reported to payroll and TDS already deducted.", "The annual salary and withholding record serves a different purpose from a current payslip, which is only a point within an evolving annual withholding process."], callout: { title: "Keep the tools in their proper roles", text: [{ text: "Use the " }, { text: "Income Tax Calculator", link: { kind: "calculator", slug: "income-tax" } }, { text: " for a supported annual ordinary-income estimate. Read the " }, { text: "core calculation guide", link: { kind: "article", slug: "new-tax-regime-slab-calculation" } }, { text: " for its limits and " }, { text: "gross versus taxable income", link: { kind: "article", slug: "gross-income-vs-taxable-income" } }, { text: " for the expected input." }] } },
      { id: "not-payroll", heading: "The calculator does not simulate payroll", paragraphs: ["It does not generate monthly TDS, an employer withholding schedule or a payslip. It does not account for TDS already deducted, proof workflows, payroll adjustments or employer-specific timing. Its output does not replace payroll records or the final filing computation."] },
    ],
    faq: [{ question: "Should monthly TDS equal annual calculator tax divided by 12?", answer: "Not necessarily. Payroll uses an annual estimate that can change during the year and can adjust earlier excesses or deficiencies." }, { question: "Does a different calculator result mean payroll is wrong?", answer: "No. First compare the period, regime, income inputs, declarations, previous-employer details and tax already deducted." }],
  },
] satisfies readonly Article[];
