import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "@/components/site/InfoPage";
import { pageMetadata } from "@/lib/content/seo";

export const metadata: Metadata = pageMetadata({ title: "Editorial Policy | ArthaSiddhi", description: "How ArthaSiddhi researches, verifies, updates, and corrects its financial education and calculator-based content.", path: "/editorial-policy" });

export default function EditorialPolicyPage() {
  return (
    <InfoPage eyebrow="Trust & transparency" title="Editorial Policy" description="How ArthaSiddhi approaches research, rule-sensitive information, numerical examples, editorial tools, and corrections. Last updated: 23 August 2026.">
      <section><h2 className="text-2xl font-bold text-slate-950">Purpose and responsibility</h2><p className="mt-3">ArthaSiddhi publishes financial education and calculator-based information to help users understand concepts and explore scenarios. The material is general information, not personalized financial, investment, tax, legal, or lending advice. Publication responsibility remains with the publisher.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Research and sources</h2><p className="mt-3">Sources are selected according to the subject. They may include government and regulator websites, statutory or rule documents, primary institutional material, calculator-engine outputs, and other appropriate reliable sources. Rule-sensitive information is checked against relevant official or primary sources where applicable; not every article requires every type of source.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Evergreen and rule-sensitive content</h2><p className="mt-3">Some concepts and calculation methods are relatively evergreen. Other information depends on current thresholds, rates, regulations, schemes, or official guidance. Rule-sensitive content can therefore require reverification when its applicable period changes or reliable new information becomes available. Pages may show effective periods, verification dates, and sources when those details are relevant.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Numerical examples</h2><p className="mt-3">Calculator-related examples may be reconciled with ArthaSiddhi’s calculation logic where appropriate. Inputs, assumptions, and context still determine what an example means. The <Link href="/methodology" className="font-semibold text-emerald-700 underline underline-offset-4">Calculator Methodology</Link> explains the general approach.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Technology and AI-assisted tools</h2><p className="mt-3">Technology and AI-assisted tools may support research, drafting, editing, testing, and consistency work. They do not independently publish content or replace editorial responsibility. Rule-sensitive financial information should be checked against appropriate official or primary sources where applicable.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Corrections</h2><p className="mt-3">Users may report suspected factual errors, calculation problems, outdated rule-sensitive information, or broken or misleading content by emailing <a href="mailto:contact@arthasiddhi.com" className="font-semibold text-emerald-700 underline underline-offset-4">contact@arthasiddhi.com</a>. Include the page address and a clear description of the issue. Reported issues may be reviewed and corrected where warranted; no response time, correction time, individual reply, or public correction log is guaranteed.</p></section>
      <section><h2 className="text-2xl font-bold text-slate-950">Editorial independence</h2><p className="mt-3">At present, ArthaSiddhi does not carry advertising, affiliate links, sponsorships, or paid placements. If commercial relationships are introduced, relevant disclosures should accompany affected content.</p><p className="mt-3">For other questions, use the <Link href="/contact" className="font-semibold text-emerald-700 underline underline-offset-4">Contact page</Link>.</p></section>
    </InfoPage>
  );
}
