import { describe, expect, it } from "vitest";
import { epfRuleSet, financialRuleSets, gratuityRuleSet, incomeTaxRuleSet, npsRuleSet, ppfRuleSet } from "../../lib/financial-rules/rule-sets";

describe("financial rule registry", () => {
  it("uses stable, unique rule-set IDs", () => { const ids = Object.values(financialRuleSets).map((ruleSet) => ruleSet.id); expect(new Set(ids).size).toBe(6); expect(ids).toEqual(["income-tax-tax-year-2026-27", "ppf-scheme-2019-amended-2020", "gst-generic-arithmetic-2026-08", "epf-schemes-contributions-2026-08", "nps-all-citizen-exits-2026-07", "gratuity-social-security-code-2025-11"]); });
  it("uses the current Act's tax-year identity without inventing an assessment year", () => { expect(incomeTaxRuleSet.effectivePeriod).toBe("Tax Year 2026–27 (FY 2026–27)"); expect(incomeTaxRuleSet.periodLabels).toEqual([{ label: "Applicable Tax Year", value: "Tax Year 2026–27" }, { label: "Corresponding Financial Year", value: "FY 2026–27" }]); expect(JSON.stringify(incomeTaxRuleSet.periodLabels)).not.toContain("Assessment Year"); });
  it("records the Tax Year 2026–27 income-tax rules", () => expect(incomeTaxRuleSet.rules).toMatchObject({ maximumSupportedIncome: 5_000_000, cessRate: 4, newRegime: { rebateIncomeLimit: 1_200_000, maximumRebate: 60_000, marginalReliefAboveRebateLimit: true, slabs: [{ upTo: 400_000, rate: 0 }, { upTo: 800_000, rate: 5 }, { upTo: 1_200_000, rate: 10 }, { upTo: 1_600_000, rate: 15 }, { upTo: 2_000_000, rate: 20 }, { upTo: 2_400_000, rate: 25 }, { upTo: null, rate: 30 }] } }));
  it("configures the current All Citizen age and exit boundaries", () => expect(npsRuleSet.rules).toMatchObject({ subscriberModel: "all-citizen", minimumCurrentAge: 18, maximumRetirementAge: 85, minimumAnnuityAllocation: 20, maximumAnnuityAllocation: 100, normalExit: { fullWithdrawalThreshold: 800_000, intermediateCorpusThreshold: 1_200_000, maximumDirectLumpSumInIntermediateBand: 600_000, maximumLumpSumAllocation: 80, minimumAnnuityAllocation: 20 }, prematureExit: { fullWithdrawalThreshold: 500_000, maximumLumpSumAllocation: 20, minimumAnnuityAllocation: 80 } }));
  it("records EPF standard, exception and interest-status boundaries", () => expect(epfRuleSet.rules).toMatchObject({ standardEmployeeRate: 12, standardEmployerRate: 12, qualifyingReducedRate: 10, epsDiversionRate: 8.33, epsWageCeiling: 15_000, higherWageContributionRequiresJointRequest: true, employerNeedNotMatchVoluntaryExcess: true, ordinaryWageCeilingAppliesToInternationalWorkers: false, approvedInterestPeriod: "FY 2024–25", approvedInterestRate: 8.25, recommendedInterestPeriod: "FY 2025–26", recommendedInterestRate: 8.25, recommendedInterestStatus: "cbt-recommendation-pending-government-notification" }));
  it("records the narrow PPF scheme facts used by content", () => expect(ppfRuleSet.rules).toEqual({ schemeName: "Public Provident Fund Scheme, 2019", minimumAnnualContribution: 500, maximumAnnualContribution: 150_000, maturityYearsFromEndOfOpeningYear: 15, extensionBlockYears: 5, extensionOptionDeadlineYears: 1, interestEligibleBalanceFromDay: 5, interestCreditedAnnually: true }));
  it("records the operative Gratuity formula, boundary and ceiling", () => expect(gratuityRuleSet.rules).toMatchObject({ ordinaryMonthlyRatedNumerator: 15, ordinaryMonthlyRatedDenominator: 26, additionalMonthsMustExceed: 6, generalContinuousServiceYears: 5, deathException: true, disablementException: true, statutoryCeiling: 2_000_000, betterTermsMayApply: true }));
  it("records a verification date and official HTTPS sources for every rule set", () => { for (const ruleSet of Object.values(financialRuleSets)) { expect(ruleSet.lastVerified).toMatch(/^\d{4}-\d{2}-\d{2}$/); expect(ruleSet.sources.length).toBeGreaterThan(0); for (const source of ruleSet.sources) { expect(source.authority).toBeTruthy(); expect(source.reference).toMatch(/^https:\/\//); expect(source.reference).not.toMatch(/blog|newspaper|affiliate/i); } } });
  it("classifies and dates every income-tax source as official", () => { expect(incomeTaxRuleSet.lastVerified).toBe("2026-08-23"); for (const source of incomeTaxRuleSet.sources) { expect(source.sourceType).toBe("official"); expect(source.accessedAt).toBe("2026-08-23"); expect(new URL(source.reference).hostname).toMatch(/(?:incometaxindia|indiabudget)\.gov\.in$/); } });
});
