import { describe, expect, it } from "vitest";
import { financialRuleSets, incomeTaxRuleSet, npsRuleSet, ppfRuleSet } from "../../lib/financial-rules/rule-sets";

describe("financial rule registry", () => {
  it("uses stable, unique rule-set IDs", () => { const ids = Object.values(financialRuleSets).map((ruleSet) => ruleSet.id); expect(new Set(ids).size).toBe(5); expect(ids).toEqual(["income-tax-fy-2025-26-ay-2026-27", "ppf-scheme-2019-amended-2020", "gst-generic-arithmetic-2026-08", "epf-standard-contributions-2026-08", "nps-normal-exit-illustration-2026-08"]); });
  it("identifies both applicable income-tax periods", () => { expect(incomeTaxRuleSet.effectivePeriod).toBe("FY 2025–26 / AY 2026–27"); expect(incomeTaxRuleSet.periodLabels).toEqual([{ label: "Applicable Financial Year", value: "FY 2025–26" }, { label: "Applicable Assessment Year", value: "AY 2026–27" }]); });
  it("records the FY 2025–26 income-tax rules", () => expect(incomeTaxRuleSet.rules).toMatchObject({ maximumSupportedIncome: 5_000_000, cessRate: 4, newRegime: { rebateIncomeLimit: 1_200_000, maximumRebate: 60_000, marginalReliefAboveRebateLimit: true, slabs: [{ upTo: 400_000, rate: 0 }, { upTo: 800_000, rate: 5 }, { upTo: 1_200_000, rate: 10 }, { upTo: 1_600_000, rate: 15 }, { upTo: 2_000_000, rate: 20 }, { upTo: 2_400_000, rate: 25 }, { upTo: null, rate: 30 }] } }));
  it("configures the All Citizen Model normal-exit illustration at a 20% minimum annuity allocation", () => expect(npsRuleSet.rules).toMatchObject({ minimumAnnuityAllocation: 20, maximumAnnuityAllocation: 100 }));
  it("records the narrow PPF scheme facts used by content", () => expect(ppfRuleSet.rules).toEqual({ schemeName: "Public Provident Fund Scheme, 2019", minimumAnnualContribution: 500, maximumAnnualContribution: 150_000, maturityYearsFromEndOfOpeningYear: 15, extensionBlockYears: 5, extensionOptionDeadlineYears: 1, interestEligibleBalanceFromDay: 5, interestCreditedAnnually: true }));
  it("records a verification date and official HTTPS sources for every rule set", () => { for (const ruleSet of Object.values(financialRuleSets)) { expect(ruleSet.lastVerified).toMatch(/^\d{4}-\d{2}-\d{2}$/); expect(ruleSet.sources.length).toBeGreaterThan(0); for (const source of ruleSet.sources) { expect(source.authority).toBeTruthy(); expect(source.reference).toMatch(/^https:\/\//); expect(source.reference).not.toMatch(/blog|newspaper|affiliate/i); } } });
  it("classifies and dates every income-tax source as official", () => { for (const source of incomeTaxRuleSet.sources) { expect(source.sourceType).toBe("official"); expect(source.accessedAt).toBe("2026-08-18"); } });
});
