"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  calculateCagr,
  calculateGratuity,
  calculateInflation,
  calculateLumpsum,
  calculatePpf,
  calculateRd,
  calculateStepUpSip,
  calculateSwp,
  type InflationMode,
  type PpfScheduleRow,
} from "@/lib/calculator/expanded-calculators";
import { formatIndianCurrency, formatNumber, formatPercentage } from "@/lib/calculator/formatting";
import { CalculatorInput } from "./CalculatorInput";
import { CalculatorResult } from "./CalculatorResult";

type ExpandedSlug = "ppf" | "rd" | "lumpsum" | "cagr" | "step-up-sip" | "gratuity" | "swp" | "inflation";
type Field = { id: string; label: string; defaultValue: string; min: number; max: number; step: number; prefix?: string; hint?: string };
type DisplayResult = { label: string; value: string; emphasis?: boolean };
type Calculation = { results: DisplayResult[]; schedule?: PpfScheduleRow[] };
type Config = { detailsTitle: string; resultsTitle: string; resultsDescription: string; fields: Field[]; how: string; disclosures: string[] };

const configs: Record<ExpandedSlug, Config> = {
  ppf: { detailsTitle: "PPF assumptions", resultsTitle: "Estimated PPF value", resultsDescription: "A simplified annual accumulation estimate.", fields: [{ id: "annualContribution", label: "Annual contribution (INR)", defaultValue: "150000", min: 0, max: 100000000000, step: 5000, prefix: "₹" }, { id: "annualInterestRate", label: "Assumed annual interest rate (%)", defaultValue: "7.1", min: 0, max: 100, step: 0.1, hint: "Editable assumption; Government-notified PPF rates can change." }, { id: "tenureYears", label: "Investment tenure (years)", defaultValue: "15", min: 1, max: 100, step: 1 }], how: "The estimate adds the entered contribution at the beginning of each year, then applies the same entered annual rate to that year's balance.", disclosures: ["PPF interest rates are periodically notified by the Government and can change.", "Actual interest calculation and credit depend on applicable scheme rules and deposit timing; this simplified annual estimate is illustrative."] },
  rd: { detailsTitle: "Recurring deposit assumptions", resultsTitle: "Estimated RD maturity", resultsDescription: "A generic beginning-of-month deposit model.", fields: [{ id: "monthlyDeposit", label: "Monthly deposit (INR)", defaultValue: "5000", min: 0, max: 100000000000, step: 500, prefix: "₹" }, { id: "annualInterestRate", label: "Annual interest rate (%)", defaultValue: "7", min: 0, max: 100, step: 0.1 }, { id: "tenureYears", label: "Tenure (years)", defaultValue: "5", min: 1, max: 100, step: 1 }], how: "Each monthly deposit is assumed at the beginning of the month and grows at a monthly-equivalent rate derived from the entered annual rate.", disclosures: ["This is an illustrative generic model and may not reproduce every bank or post-office RD product convention."] },
  lumpsum: { detailsTitle: "Investment assumptions", resultsTitle: "Estimated future value", resultsDescription: "Based on annual compounding at the entered return.", fields: [{ id: "initialInvestment", label: "Initial investment (INR)", defaultValue: "100000", min: 0, max: 100000000000, step: 1000, prefix: "₹" }, { id: "annualReturnRate", label: "Expected annual return (%)", defaultValue: "12", min: 0, max: 100, step: 0.1 }, { id: "investmentYears", label: "Investment period (years)", defaultValue: "10", min: 1, max: 100, step: 1 }], how: "The one-time investment compounds once per year at the same entered annual return throughout the selected period.", disclosures: ["Expected return is an assumption, not a guaranteed investment return."] },
  cagr: { detailsTitle: "Growth details", resultsTitle: "Annualized growth", resultsDescription: "The constant annualized rate connecting the two values.", fields: [{ id: "beginningValue", label: "Beginning value (INR)", defaultValue: "100000", min: 0.01, max: 100000000000, step: 1000, prefix: "₹" }, { id: "endingValue", label: "Ending value (INR)", defaultValue: "200000", min: 0, max: 100000000000, step: 1000, prefix: "₹" }, { id: "durationYears", label: "Duration (years)", defaultValue: "5", min: 1, max: 100, step: 1 }], how: "CAGR is the constant annualized growth rate that would connect the beginning and ending values over the entered duration. It is not an arithmetic average return.", disclosures: ["CAGR smooths the full period into one annualized rate and does not show year-to-year volatility."] },
  "step-up-sip": { detailsTitle: "Step-up SIP assumptions", resultsTitle: "Estimated future value", resultsDescription: "Beginning-of-month investments with an annual step-up.", fields: [{ id: "startingMonthlyInvestment", label: "Starting monthly investment (INR)", defaultValue: "5000", min: 0, max: 100000000000, step: 500, prefix: "₹" }, { id: "annualReturnRate", label: "Expected annual return (%)", defaultValue: "12", min: 0, max: 100, step: 0.1 }, { id: "investmentYears", label: "Investment period (years)", defaultValue: "10", min: 1, max: 100, step: 1 }, { id: "annualStepUpRate", label: "Annual SIP increase (%)", defaultValue: "10", min: 0, max: 100, step: 0.1 }], how: "The monthly investment stays constant for 12 months, then increases once at the beginning of each new investment year. Each contribution is made before that month's assumed return is applied.", disclosures: ["Expected returns are assumptions. Real investment returns are not constant or guaranteed."] },
  gratuity: { detailsTitle: "Service and wage details", resultsTitle: "Estimated gratuity", resultsDescription: "A general statutory-style formula estimate.", fields: [{ id: "eligibleMonthlyWage", label: "Eligible monthly wage for gratuity calculation (INR)", defaultValue: "50000", min: 0, max: 100000000000, step: 1000, prefix: "₹", hint: "Enter the wage amount applicable to the formula, not total CTC unless applicable." }, { id: "completedYears", label: "Completed years of service", defaultValue: "10", min: 0, max: 100, step: 1 }, { id: "additionalMonths", label: "Additional completed months of service", defaultValue: "0", min: 0, max: 11, step: 1 }], how: "The estimate multiplies the entered eligible monthly wage by 15/26 and by completed years. More than six additional completed months adds one year for this estimate.", disclosures: ["This calculator does not determine legal eligibility or define the wage applicable to your circumstances.", "Statutory eligibility, wage definitions, and special cases depend on applicable law and employment circumstances. Verify an actual entitlement with your employer, official rules, or a qualified professional."] },
  swp: { detailsTitle: "Withdrawal assumptions", resultsTitle: "Estimated withdrawal outcome", resultsDescription: "Return is applied before each monthly withdrawal.", fields: [{ id: "initialInvestment", label: "Initial investment (INR)", defaultValue: "1000000", min: 0, max: 100000000000, step: 10000, prefix: "₹" }, { id: "monthlyWithdrawal", label: "Monthly withdrawal (INR)", defaultValue: "10000", min: 0, max: 100000000000, step: 1000, prefix: "₹" }, { id: "annualReturnRate", label: "Expected annual return (%)", defaultValue: "8", min: 0, max: 100, step: 0.1 }, { id: "withdrawalYears", label: "Withdrawal period (years)", defaultValue: "10", min: 1, max: 100, step: 1 }], how: "For each month, the monthly-equivalent assumed return is applied first. The requested withdrawal is then deducted, limited to the available balance so the estimate never becomes negative.", disclosures: ["Investment returns are assumptions. Real market returns are not constant, and the sequence of returns can materially affect withdrawals."] },
  inflation: { detailsTitle: "Inflation assumptions", resultsTitle: "Inflation estimate", resultsDescription: "Based on one constant assumed annual inflation rate.", fields: [{ id: "currentValue", label: "Current value (INR)", defaultValue: "100000", min: 0, max: 100000000000, step: 1000, prefix: "₹" }, { id: "annualInflationRate", label: "Expected inflation rate (%)", defaultValue: "6", min: 0, max: 100, step: 0.1 }, { id: "years", label: "Number of years", defaultValue: "10", min: 1, max: 100, step: 1 }], how: "Future Cost compounds today's cost by the entered inflation rate. Purchasing Power divides today's amount by the same compounded inflation factor.", disclosures: ["Inflation is not constant. The entered rate is an assumption for illustration."] },
};

function parse(fields: Field[], values: Record<string, string>) {
  return Object.fromEntries(fields.map((field) => {
    if (values[field.id]?.trim() === "") throw new Error(`${field.label} is required.`);
    return [field.id, Number(values[field.id])];
  })) as Record<string, number>;
}

function calculate(slug: ExpandedSlug, values: Record<string, string>, mode: InflationMode): Calculation {
  const parsed = parse(configs[slug].fields, values);
  switch (slug) {
    case "ppf": { const result = calculatePpf({ annualContribution: parsed.annualContribution, annualInterestRate: parsed.annualInterestRate, tenureYears: parsed.tenureYears }); return { results: [{ label: "Total contribution", value: formatIndianCurrency(result.totalContribution) }, { label: "Estimated interest", value: formatIndianCurrency(result.interestEarned) }, { label: "Estimated maturity", value: formatIndianCurrency(result.maturityAmount), emphasis: true }], schedule: result.schedule }; }
    case "rd": { const result = calculateRd({ monthlyDeposit: parsed.monthlyDeposit, annualInterestRate: parsed.annualInterestRate, tenureYears: parsed.tenureYears }); return { results: [{ label: "Total deposits", value: formatIndianCurrency(result.totalDeposits) }, { label: "Estimated interest", value: formatIndianCurrency(result.interestEarned) }, { label: "Estimated maturity", value: formatIndianCurrency(result.maturityAmount), emphasis: true }] }; }
    case "lumpsum": { const result = calculateLumpsum({ initialInvestment: parsed.initialInvestment, annualReturnRate: parsed.annualReturnRate, investmentYears: parsed.investmentYears }); return { results: [{ label: "Invested amount", value: formatIndianCurrency(result.investedAmount) }, { label: "Estimated gain", value: formatIndianCurrency(result.estimatedGain) }, { label: "Estimated future value", value: formatIndianCurrency(result.futureValue), emphasis: true }] }; }
    case "cagr": { const result = calculateCagr({ beginningValue: parsed.beginningValue, endingValue: parsed.endingValue, durationYears: parsed.durationYears }); return { results: [{ label: "Beginning value", value: formatIndianCurrency(result.beginningValue) }, { label: "Ending value", value: formatIndianCurrency(result.endingValue) }, { label: "Absolute gain/loss", value: formatIndianCurrency(result.absoluteGainLoss) }, { label: "CAGR", value: formatPercentage(result.cagrPercentage), emphasis: true }] }; }
    case "step-up-sip": { const result = calculateStepUpSip({ startingMonthlyInvestment: parsed.startingMonthlyInvestment, annualReturnRate: parsed.annualReturnRate, investmentYears: parsed.investmentYears, annualStepUpRate: parsed.annualStepUpRate }); return { results: [{ label: "Total invested", value: formatIndianCurrency(result.totalInvested) }, { label: "Estimated returns", value: formatIndianCurrency(result.estimatedReturns) }, { label: "Estimated future value", value: formatIndianCurrency(result.futureValue), emphasis: true }, { label: "Final monthly SIP", value: formatIndianCurrency(result.finalMonthlyInvestment) }] }; }
    case "gratuity": { const result = calculateGratuity({ eligibleMonthlyWage: parsed.eligibleMonthlyWage, completedYears: parsed.completedYears, additionalMonths: parsed.additionalMonths }); return { results: [{ label: "Service counted", value: `${formatNumber(result.serviceYearsCounted)} years` }, { label: "Eligible monthly wage entered", value: formatIndianCurrency(result.eligibleMonthlyWage) }, { label: "Estimated gratuity", value: formatIndianCurrency(result.estimatedGratuity), emphasis: true }] }; }
    case "swp": { const result = calculateSwp({ initialInvestment: parsed.initialInvestment, monthlyWithdrawal: parsed.monthlyWithdrawal, annualReturnRate: parsed.annualReturnRate, withdrawalYears: parsed.withdrawalYears }); return { results: [{ label: "Initial investment", value: formatIndianCurrency(result.initialInvestment) }, { label: "Total withdrawn", value: formatIndianCurrency(result.totalWithdrawn) }, { label: "Estimated remaining balance", value: formatIndianCurrency(result.remainingBalance), emphasis: true }, { label: "Withdrawals completed", value: formatNumber(result.withdrawalsCompleted) }, { label: "Exhausted before tenure", value: result.exhaustedBeforeTenure ? "Yes" : "No" }] }; }
    case "inflation": { const result = calculateInflation({ mode, currentValue: parsed.currentValue, annualInflationRate: parsed.annualInflationRate, years: parsed.years }); return { results: mode === "future-cost" ? [{ label: "Current cost", value: formatIndianCurrency(result.currentValue) }, { label: "Estimated future cost", value: formatIndianCurrency(result.estimatedValue), emphasis: true }, { label: "Increase from assumed inflation", value: formatIndianCurrency(result.change) }] : [{ label: "Current amount", value: formatIndianCurrency(result.currentValue) }, { label: "Estimated future purchasing power", value: formatIndianCurrency(result.estimatedValue), emphasis: true }, { label: "Estimated purchasing-power erosion", value: formatIndianCurrency(result.change) }] }; }
  }
}

function fieldHasError(error: string | null, field: Field) {
  if (!error) return false;
  const fieldName = field.label.split(" (")[0];
  return error.startsWith(fieldName) || (field.id === "currentValue" && error.startsWith("Current "));
}

export function ExpandedCalculator({ slug }: { slug: ExpandedSlug }) {
  const config = configs[slug];
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(config.fields.map((field) => [field.id, field.defaultValue])));
  const [mode, setMode] = useState<InflationMode>("future-cost");
  const calculation = useMemo(() => { try { return { value: calculate(slug, values, mode), error: null as string | null }; } catch (error) { return { value: null, error: error instanceof Error ? error.message : "Unable to calculate this estimate." }; } }, [slug, values, mode]);

  return (
    <div className="space-y-8">
      <div className="grid gap-6 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
        <section aria-labelledby={`${slug}-details`} className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
          <h2 id={`${slug}-details`} className="text-lg font-semibold text-slate-950">{config.detailsTitle}</h2>
          <p className="mt-1 text-sm text-slate-600">Update any value to recalculate instantly.</p>
          {slug === "inflation" && <div className="mt-6"><label htmlFor="inflationMode" className="block text-sm font-medium text-slate-800">Calculation mode</label><select id="inflationMode" value={mode} onChange={(event) => setMode(event.target.value as InflationMode)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-base shadow-xs outline-none transition focus:border-emerald-600 focus:ring-3 focus:ring-emerald-100"><option value="future-cost">Future cost</option><option value="purchasing-power">Purchasing power</option></select></div>}
          <div className="mt-6 space-y-5">{config.fields.map((field) => <CalculatorInput key={field.id} {...field} value={values[field.id]} onChange={(value) => setValues((current) => ({ ...current, [field.id]: value }))} error={fieldHasError(calculation.error, field)} errorId={`${slug}-error`} />)}</div>
          {calculation.error && <p id={`${slug}-error`} role="alert" className="mt-5 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-sm text-red-800">{calculation.error}</p>}
        </section>
        <section aria-labelledby={`${slug}-results`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
          <h2 id={`${slug}-results`} className="text-lg font-semibold text-slate-950">{config.resultsTitle}</h2>
          <p className="mt-1 text-sm text-slate-600">{config.resultsDescription}</p>
          {calculation.value ? <div aria-live="polite" className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{calculation.value.results.map((result) => <CalculatorResult key={result.label} {...result} />)}</div> : <p className="mt-6 rounded-xl bg-slate-50 p-5 text-sm text-slate-600">Enter valid details to view your estimate.</p>}
        </section>
      </div>
      {calculation.value?.schedule && <section aria-labelledby="ppf-schedule-heading" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><h2 id="ppf-schedule-heading" className="border-b border-slate-200 px-5 py-4 text-lg font-semibold text-slate-950">Year-by-year schedule</h2><div className="overflow-x-auto"><table className="min-w-[720px] w-full text-right text-sm"><caption className="sr-only">Illustrative annual PPF accumulation schedule</caption><thead className="bg-slate-50 text-xs font-semibold tracking-wide text-slate-600 uppercase"><tr><th scope="col" className="px-5 py-3 text-left">Year</th><th scope="col" className="px-5 py-3">Opening balance</th><th scope="col" className="px-5 py-3">Contribution</th><th scope="col" className="px-5 py-3">Interest</th><th scope="col" className="px-5 py-3">Closing balance</th></tr></thead><tbody className="divide-y divide-slate-100">{calculation.value.schedule.map((row) => <tr key={row.year}><th scope="row" className="px-5 py-3 text-left font-medium">{row.year}</th><td className="px-5 py-3">{formatIndianCurrency(row.openingBalance)}</td><td className="px-5 py-3">{formatIndianCurrency(row.contribution)}</td><td className="px-5 py-3">{formatIndianCurrency(row.interest)}</td><td className="px-5 py-3">{formatIndianCurrency(row.closingBalance)}</td></tr>)}</tbody></table></div></section>}
      <section aria-labelledby={`${slug}-method`} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 id={`${slug}-method`} className="text-xl font-bold text-slate-950">How this is calculated</h2><p className="mt-3 leading-7 text-slate-700">{config.how}</p><h3 className="mt-6 font-semibold text-slate-950">Important assumptions</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-700">{config.disclosures.map((disclosure) => <li key={disclosure}>{disclosure}</li>)}</ul><p className="mt-5 text-sm text-slate-600">Review the <Link href="/disclaimer" className="font-semibold text-emerald-700 underline underline-offset-4 focus:outline-none focus:ring-3 focus:ring-emerald-100">Financial Disclaimer</Link> before using an estimate for an important decision.</p></section>
    </div>
  );
}
