"use client";

import { useMemo, useState } from "react";
import { calculateFd } from "@/lib/calculator/fd-calculator";
import type { CompoundingFrequency } from "@/lib/calculator/types";
import { formatIndianCurrency } from "@/lib/calculator/formatting";
import { CalculatorInput } from "./CalculatorInput";
import { CalculatorResult } from "./CalculatorResult";

const defaults = { principal: "100000", annualInterestRate: "7", tenureYears: "3", compoundingFrequency: "quarterly" as CompoundingFrequency };

export function FdCalculator() {
  const [values, setValues] = useState(defaults);
  const calculation = useMemo(() => { try { return { result: calculateFd({ principal: Number(values.principal), annualInterestRate: Number(values.annualInterestRate), tenureYears: Number(values.tenureYears), compoundingFrequency: values.compoundingFrequency }), error: null }; } catch (error) { return { result: null, error: error instanceof Error ? error.message : "Unable to calculate this deposit." }; } }, [values]);
  const update = (field: "principal" | "annualInterestRate" | "tenureYears") => (value: string) => setValues((current) => ({ ...current, [field]: value }));
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><section aria-labelledby="fd-details" className="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 id="fd-details" className="text-lg font-semibold text-slate-950">Deposit details</h2><p className="mt-1 text-sm text-slate-600">Update any value to recalculate instantly.</p><div className="mt-6 space-y-5"><CalculatorInput id="principal" label="Principal amount (INR)" value={values.principal} onChange={update("principal")} min={0.01} max={100000000000} step={1000} prefix="₹" error={Boolean(calculation.error)} errorId="fd-error" /><CalculatorInput id="annualInterestRate" label="Annual interest rate (%)" value={values.annualInterestRate} onChange={update("annualInterestRate")} min={0} max={100} step={0.01} error={Boolean(calculation.error)} errorId="fd-error" /><CalculatorInput id="tenureYears" label="Tenure (years)" value={values.tenureYears} onChange={update("tenureYears")} min={0.01} max={100} step={0.25} error={Boolean(calculation.error)} errorId="fd-error" /><div><label htmlFor="compoundingFrequency" className="block text-sm font-medium text-slate-800">Compounding frequency</label><select id="compoundingFrequency" value={values.compoundingFrequency} onChange={(event) => setValues((current) => ({ ...current, compoundingFrequency: event.target.value as CompoundingFrequency }))} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-base shadow-xs outline-none transition focus:border-emerald-600 focus:ring-3 focus:ring-emerald-100"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="half-yearly">Half-yearly</option><option value="yearly">Yearly</option></select></div></div>{calculation.error && <p id="fd-error" role="alert" className="mt-5 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-sm text-red-800">{calculation.error}</p>}</section><section aria-labelledby="fd-results" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 id="fd-results" className="text-lg font-semibold text-slate-950">Your maturity estimate</h2><p className="mt-1 text-sm text-slate-600">Based on the selected compounding frequency.</p>{calculation.result ? <div aria-live="polite" className="mt-6 grid gap-3 sm:grid-cols-3"><CalculatorResult label="Principal" value={formatIndianCurrency(calculation.result.principal)} /><CalculatorResult label="Interest earned" value={formatIndianCurrency(calculation.result.interestEarned)} /><CalculatorResult label="Maturity amount" value={formatIndianCurrency(calculation.result.maturityAmount)} emphasis /></div> : <p className="mt-6 rounded-xl bg-slate-50 p-5 text-sm text-slate-600">Enter valid deposit details to view your estimate.</p>}</section></div>;
}
